### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by CairX** [CairX/extract-colors-py#16]
According to [PEP 478 - Python 3.5 Release Schedule](https://www.python.org/dev/peps/pep-0478/) the final version should soon be released and end-of-life reached. A more accurate data can be found in [Python Developer’s Guide - Status of Python branches](https://devguide.python.org/#status-of-python-branches).

Pillow are preparing for the change in [Drop support for EOL Python 3.5 #4746](https://github.com/python-pillow/Pillow/pull/4746) and [Drop support for EOL Python 3.5 #4794](https://github.com/python-pillow/Pillow/pull/4794). So far it seems the aim is for the change to be in version [8.0.0](https://github.com/python-pillow/Pillow/issues/4764) which is scheduled for the 15th of October 2020.

**Comment by hugovk** [comment]
Please see PR #25.
