### ISSUE TITLE
Export Extracted Color to GPL 

### ISSUE THREAD

**Issue by raniaamina** [CairX/extract-colors-py#23]
Hi, thank for creating this tool, very helpful for me as designer.

I don't no it make sense or do-able or not, but it will more helpful ir this tools can export the extracted color into GPL file so user can use the extracted color result directly in their application like Inkscape or other.

Thank you very much, love this tool.

Rania Amina

**Comment by CairX** [comment]
Thank you so much for sharing your use case. It's something that has never cross my mind but sounds like a fantastic idea. I will investigate the file format and give it a go, can't promise any expected time frame though.

I have a follow up questions for you, are there other palette formats that would be interesting to support? Not something I work with very often.

**Comment by raniaamina** [comment]
Great, thank you very much, i'll wait it.

Here is some color and swatch formats, hope it help. 
http://www.selapa.net/swatches/colors/fileformats.php

In case of me that work with open format, GPL is very familar and most of open source application used this format.
If it work, i can promote this tools into (Gimpscape Community)[https://gimpscape.org]. I think most of designer will very helped with this feature. 

Thanks,
Rania Amina

**Comment by raniaamina** [comment]
@CairX, i try to make a bash script to convert extcolors output into gpl format.

[paletin.zip](https://github.com/CairX/extract-colors-py/files/5316336/paletin.zip)

The usage is:
`bash paletin img-file.jpg palete-name`

It works for me, but will be greate if extcolors have it feature by default.

**Comment by CairX** [comment]
Thank you for your information. Support has now been added for GPL and a release has been made for it, version 0.3.0.

**Comment by raniaamina** [comment]
Thank you, i'll check it soon
