### ISSUE TITLE
Add support for Pyton 3.9

### ISSUE THREAD

**Issue by CairX** [CairX/extract-colors-py#24]
The first official release of Python 3.9 is planned for October 5th according to [PEP 596 - Python 3.9 Release Schedule](https://www.python.org/dev/peps/pep-0596/).

Pillow won't support upgrading to Python 3.9 until version [8.0.0](https://github.com/python-pillow/Pillow/issues/4764) which is scheduled for the 15th of October 2020.

Work has begun in branch `python-3.9`.

**Comment by CairX** [comment]
Pillow won't support upgrading to Python 3.9 until version [8.0.0](https://github.com/python-pillow/Pillow/issues/4764) which is scheduled for the 15th of October 2020.

**Comment by hugovk** [comment]
Pillow 8.0.0 supporting Python 3.9 is now out!

* https://pillow.readthedocs.io/en/stable/releasenotes/8.0.0.html
* https://pypi.org/project/Pillow/8.0.0/
* https://twitter.com/PythonPillow/status/1316452445824921602
