### ISSUE TITLE
Doesn't work with Python2.7

### ISSUE THREAD

**Issue by BondarenkoArtur** [CairX/extract-colors-py#7]
I've installed extcolors with pip2
and it's just doesn't work.
On python 3 works well...

I was using this image
![rainbow](https://i.imgur.com/7tQtCDj.png)
In python2.7 i've got
```
 $ extcolors ~/Downloads/pic.png 
Extracted colors:
(9.0, 9.0, 9.0):   0.00% (32)
(255.0, 255.0, 255.0):   0.00% (32)

Pixels in output: 64 of 960
Traceback (most recent call last):
  File "/usr/bin/extcolors", line 11, in <module>
    load_entry_point('extcolors==0.1.0', 'console_scripts', 'extcolors')()
  File "/usr/lib/python2.7/site-packages/extcolors/__init__.py", line 153, in main
    image_result(counter, 150, filename)
  File "/usr/lib/python2.7/site-packages/extcolors/__init__.py", line 80, in image_result
    result = Image.new("RGBA", (width, height), (0, 0, 0, 0))
  File "/usr/lib/python2.7/site-packages/PIL/Image.py", line 2331, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: integer argument expected, got float
```

But in python3 everything just fine
```
extcolors ~/Downloads/pic.png                      
Extracted colors:
(171, 255, 1)  :  20.00% (192)
(30, 2, 255)   :  20.00% (192)
(255, 44, 1)   :  15.00% (144)
(1, 255, 137)  :  10.00% (96)
(255, 192, 1)  :   5.00% (48)
(1, 255, 212)  :   5.00% (48)
(1, 207, 255)  :   5.00% (48)
(1, 132, 255)  :   5.00% (48)
(241, 0, 251)  :   5.00% (48)
(255, 1, 192)  :   5.00% (48)
(255, 1, 117)  :   5.00% (48)

Pixels in output: 960 of 960
```

**Comment by CairX** [comment]
Thank you for the issue report.

The package has a dependency to [Pillow](https://pypi.org/project/Pillow/) which doesn't support Python version 2.7. I will update the package with the same Python requirement as Pillow.

**Comment by CairX** [comment]
A late update to this topic. However I have added support for Python 2.7, with the changes uploaded to [PyPI](https://pypi.org/project/extcolors/) in version 0.1.2.

The original fault was mine for misunderstanding the Python version requirements of Pillow. Currently the requirements are `>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*`.
